### ISSUE TITLE
amr64 docker ?

### ISSUE THREAD

**Issue by gedw99** [koddr/wonderful-readme-stats#1]
got this on my arm m2 Mac book.

```
Downloaded newer image for koddr/wonderful-readme-stats:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

looks like the CI only makes amd64 ?

**Comment by koddr** [comment]
Hi, @gedw99 

Glad to see you here 😉 Thanks for this issue.

The `wonderful-readme-stats` project aims to work on the **remote** servers with GNU/Linux (`amd64` or `arm64`) only. 

Local running possible through one of these ways:

1. Clone repository and build from the source;
2. Download the ready-made binaries from Assets section on the Release page.

In `v1.0.1` patch, by the way, I've added support for `linux/arm64` architecture to the Docker image.
